### ISSUE TITLE
A bit of bug?

### ISSUE THREAD

**Issue by dgreatblack** [ecapuano/web-traffic-generator#3]
I uploaded the "config.py" and "gen.py" to a host and ran the "gen.py" and it returned a 404 error. After a series of research, I resulted in adding ``` print "Content-type: text/html\n\n" ``` right after ``` #!/usr/bin/python ``` and it didn't return 404, but a blank page in the browser. 
So i don't know if it is how the script was designed to work, I didn't see any confirmation as to if it worked or not. So how was this programmed to show that the script executed? thanks.

**Comment by ecapuano** [comment]
what URLs are you using in config.py ? A 404 is a web server error - not something my script generates.

**Comment by ecapuano** [comment]
can you copy/paste the output you're seeing?

**Comment by dgreatblack** [comment]
The output doesn't show anything. Just a blank white screen.

**Comment by dgreatblack** [comment]
public_html/cgi-bin/gen.py
public_html/cgi-bin/config.py

You didn't make any comment on the code I added to avoid the 404. I think the browser couldn't detect it was a  .py  until I added ```print "Content-type: text/html\n\n"```. Then it return a 404 but it displayed a blank page. 
Please re-run on your own end. What am I supposed to see if it works?

**Comment by ecapuano** [comment]
I just did a fresh clone of the repo and ran it without issues... Here is what the output should look like.

```
bash$ python gen.py
Traffic generator started...
----------------------------
https://github.com/ecapuano/web-traffic-generator

Clcking 5 links deep into 7 different root URLs,
waiting between 5 and 10 seconds between requests.

This script will run indefinitely. Ctrl+C to stop.
```

**Comment by ecapuano** [comment]
You mention having a blank white screen.... but this script does not render anything on a screen other than standard out on your console... There is no web browser involvement.

**Comment by dgreatblack** [comment]
Well, my WHM said that they have Python version 2.6 installed on the server I am using. So I don't know the version of Python your script is running on.

**Comment by dgreatblack** [comment]
Is there like a vivid video of how you ran it and all the details concerned?

**Comment by ecapuano** [comment]
Here ya go - from 0 to finish. The part where the code breaks is me hitting Ctrl+C so I can demonstrate when Debug is enabled. 

https://asciinema.org/a/147170
